#!/bin/bash
#
# verify_secrets.sh
#
# Reproducible verification of the CKAN session/JWT secret resolution logic
# from start_ckan.sh.  This script extracts and runs the resolve_secret
# helper (exactly as it appears in images/ckan/*/setup/app/start_ckan.sh)
# against every combination of env-var inputs we care about, and prints
# PASS / FAIL for each case.
#
# It also prints step-by-step instructions for an end-to-end verification
# using docker-compose (see the "E2E_VERIFICATION" section at the bottom).
#
set -u

PASS=0
FAIL=0

pass() { echo "  [PASS] $1"; PASS=$((PASS+1)); }
fail() { echo "  [FAIL] $1  (got: '$2')"; FAIL=$((FAIL+1)); }

# ---------------------------------------------------------------------------
# Exact copy of resolve_secret from images/ckan/*/setup/app/start_ckan.sh
# KEEP THIS SYNCHRONISED when editing the startup scripts.
# ---------------------------------------------------------------------------
resolve_secret() {
	local envvar_ckanstyle="$1"
	local envvar_legacy="$2"
	local val=""
	if [[ -n "${!envvar_ckanstyle+x}" && -n "${!envvar_ckanstyle}" ]]; then
		val="${!envvar_ckanstyle}"
	elif [[ -n "${!envvar_legacy+x}" && -n "${!envvar_legacy}" ]]; then
		val="${!envvar_legacy}"
	fi
	if [[ "$val" == string:* ]]; then
		val="${val#string:}"
	fi
	if [[ "$val" == "CHANGE_ME" ]]; then
		val=""
	fi
	echo "$val"
}

run_test() {
	local desc="$1"
	local expected="$2"
	unset CKAN___TEST BEAKER_TEST
	# shellcheck disable=SC2015
	[[ $# -ge 3 && -n "$3" ]] && export CKAN___TEST="$3" || true
	# shellcheck disable=SC2015
	[[ $# -ge 4 && -n "$4" ]] && export BEAKER_TEST="$4" || true

	local actual
	actual="$(resolve_secret CKAN___TEST BEAKER_TEST)"
	if [[ "$actual" == "$expected" ]]; then
		pass "$desc"
	else
		fail "$desc" "$actual"
	fi
	unset CKAN___TEST BEAKER_TEST
}

echo "============================================================"
echo " Unit tests – resolve_secret() from start_ckan.sh"
echo "============================================================"

echo
echo "-- Path A: secrets PROVIDED via env (must be preserved) --"

run_test \
	"CKAN___ style (no prefix)" \
	"my-beaker-secret" \
	"my-beaker-secret" \
	""

run_test \
	"CKAN___ style with string: prefix (prefix stripped)" \
	"my-jwt-secret" \
	"string:my-jwt-secret" \
	""

run_test \
	"Legacy BEAKER_ style used when CKAN___ style absent" \
	"legacy-secret" \
	"" \
	"legacy-secret"

run_test \
	"CKAN___ style takes precedence over legacy" \
	"ckanstyle-wins" \
	"ckanstyle-wins" \
	"legacy-ignored"

run_test \
	"CKAN___ style with string:CHANGE_ME -> treated as empty (auto-gen path)" \
	"" \
	"string:CHANGE_ME" \
	""

echo
echo "-- Path B: secrets NOT provided -> must be empty (trigger auto-gen) --"

run_test \
	"Both vars UNSET" \
	""

run_test \
	"CKAN___ exactly 'CHANGE_ME' -> treated as empty" \
	"" \
	"CHANGE_ME" \
	""

run_test \
	"Legacy exactly 'CHANGE_ME' -> treated as empty" \
	"" \
	"" \
	"CHANGE_ME"

echo
echo "============================================================"
echo " Result: $PASS passed, $FAIL failed"
echo "============================================================"
[[ $FAIL -eq 0 ]] || exit 1

# ---------------------------------------------------------------------------
# End-to-end verification instructions using docker-compose.
# ---------------------------------------------------------------------------
cat <<'E2E_VERIFICATION'

============================================================
 E2E verification – docker-compose
============================================================

The unit tests above prove the bash helper logic.  To confirm
behaviour against a real CKAN container, run the steps below
from the compose/ directory.


Scenario 1 – Secrets ARE provided  →  values should be preserved
----------------------------------------------------------------
1. Edit config/ckan/.env  and set:

       CKAN___BEAKER__SESSION__SECRET=test-beaker-000
       CKAN___API_TOKEN__JWT__ENCODE__SECRET=string:test-jwt-111
       CKAN___API_TOKEN__JWT__DECODE__SECRET=string:test-jwt-222

2. Start CKAN and print the effective values from production.ini:

       cd compose/
       docker compose up -d --build ckan
       docker compose exec ckan ckan config-tool /app/production.ini \
           -g beaker.session.secret \
           -g api_token.jwt.encode.secret \
           -g api_token.jwt.decode.secret

3. Expected output:

       beaker.session.secret = test-beaker-000
       api_token.jwt.encode.secret = string:test-jwt-111
       api_token.jwt.decode.secret = string:test-jwt-222

   Also check the container log for "Using value from environment":

       docker compose logs ckan | grep -E '\[(beaker|api_token|WTF)'


Scenario 2 – Secrets NOT provided  →  values should be autogenerated
--------------------------------------------------------------------
1. Edit config/ckan/.env  and SET BACK TO:

       CKAN___BEAKER__SESSION__SECRET=CHANGE_ME
       CKAN___API_TOKEN__JWT__ENCODE__SECRET=string:CHANGE_ME
       CKAN___API_TOKEN__JWT__DECODE__SECRET=string:CHANGE_ME

   (or simply comment the three lines out entirely).

2. Destroy the old container and its volume so we start from a
   completely fresh production.ini:

       cd compose/
       docker compose down -v
       docker compose up -d --build ckan
       docker compose exec ckan ckan config-tool /app/production.ini \
           -g beaker.session.secret \
           -g api_token.jwt.encode.secret \
           -g api_token.jwt.decode.secret

3. Expected behaviour:
   - Values are non-empty random-looking strings
     (i.e. NOT the literal "CHANGE_ME").
   - Container log shows "Not set, autogenerating":

       docker compose logs ckan | grep -E '\[(beaker|api_token|WTF)'

4. Restart the container WITHOUT removing the volume:

       docker compose restart ckan

   After restart the 3 values in production.ini MUST be IDENTICAL
   to before the restart (they are persisted, not regenerated).
   This proves we only regenerate when the ini value is truly
   missing / empty.

E2E_VERIFICATION
